// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWriglGj3ZKB2KzvEm5GhXw8TsMjyMKks',
    appId: '1:285207710216:android:f096f1f5d11277fb525fbd',
    messagingSenderId: '285207710216',
    projectId: 'shopping-d89aa',
    storageBucket: 'shopping-d89aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ3UDE7pxU_PiBGwuX87eDWdkHDUxlp6Q',
    appId: '1:439122712492:ios:4da545d17c20c73afb4c09',
    messagingSenderId: '439122712492',
    projectId: 'mshop-d40f8',
    storageBucket: 'mshop-d40f8.firebasestorage.app',
    iosBundleId: 'com.app.mshop',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOc6RFDFi1q0NfJZReRypSkL-w3FxMYHY',
    appId: '1:439122712492:web:e85d058062d51c8cfb4c09',
    messagingSenderId: '439122712492',
    projectId: 'mshop-d40f8',
    authDomain: 'mshop-d40f8.firebaseapp.com',
    storageBucket: 'mshop-d40f8.firebasestorage.app',
    measurementId: 'G-KLKVPE1NQ4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ3UDE7pxU_PiBGwuX87eDWdkHDUxlp6Q',
    appId: '1:439122712492:ios:2b372c35b6cb8f9dfb4c09',
    messagingSenderId: '439122712492',
    projectId: 'mshop-d40f8',
    storageBucket: 'mshop-d40f8.firebasestorage.app',
    iosBundleId: 'com.example.hyperLocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOc6RFDFi1q0NfJZReRypSkL-w3FxMYHY',
    appId: '1:439122712492:web:0522497f5a1bb30bfb4c09',
    messagingSenderId: '439122712492',
    projectId: 'mshop-d40f8',
    authDomain: 'mshop-d40f8.firebaseapp.com',
    storageBucket: 'mshop-d40f8.firebasestorage.app',
    measurementId: 'G-HZYCP4ZPCY',
  );
}
